Repository Part2-Team-2/sb03-HRBank-team2, pull requests merged in 2025-06, with the labels that each got.

#11 fix: 코드 래빗 문제 해결
  .idea/.gitignore
  .idea/material_theme_project_new.xml
  HRBank/.coderabbit.yaml
Labels: Bug

#16 feat: 첨부파일 관리기능 추가
  .DS_Store
  .gitignore
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/dto/BinaryContentResponseDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/entity/BinaryContent.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/mapper/BinaryContentMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/repository/BinaryContentRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/service/BinaryContentService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/service/BinaryContentServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/global/base/BaseEntity.java
Labels: Feat

#20 feat: 직원 수 조회 기능 추가
  HRBank/build.gradle
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/entity/Employee.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/global/config/QuerydslConfig.java
Labels: Feat

#19 feat: 특정 부서 조회 기능 추가
  .idea/workspace.xml
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/entity/Department.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentServiceImpl.java
Labels: Feat

#22 feat: binary content 글로벌 익셉션 적용, csv 파일 생성 로직 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/dto/BackupDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/entity/Backup.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/entity/BackupStatus.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/mapper/BackupMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/entity/BinaryContent.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/mapper/BinaryContentMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/employee_backup_156_20250604_080455.csv
Labels: Feat

#27 feat: 직원 분포 조회 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/dto/data/EmployeeDistributionDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Feat

#26 feat: 부서 정보 수정 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/dto/request/DepartmentUpdateRequest.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/mapper/DepartmentMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentServiceImpl.java
Labels: Feat

#33 refactor: 직원 분포 조회 기능 보완
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Refactor

#34 refactor: 직원 이력 관리 기능 보완
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/dto/data/ChangeLogDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/entity/ChangeLog.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/entity/ChangeLogDiff.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogDiffRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogServiceImpl.java
Labels: Refactor

#24 feat: 데이터 백업 생성 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/dto/BackupDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/entity/Backup.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/entity/BinaryContent.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
Labels: Feat

#39 feat: 부서 전체 조회 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/controller/DepartmentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/entity/Department.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/mapper/DepartmentMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/repository/DepartmentRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/repository/DepartmentRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/repository/DepartmentRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/global/dto/CursorPageResponse.java
Labels: Feat

#44 feat: 데이터 백업 목록 조회 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/aop/BackupSynchronizedExecutionAspect.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/aop/SynchronizedExecution.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/dto/BackupDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/dto/CursorPageResponseBackupDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepositoryCustomImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/temporary/TempEmployeeDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/repository/BinaryContentRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupBinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupBinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/global/exception/CustomBackupSynchronizedException.java
  HRBank/src/main/java/org/yebigun/hrbank/global/exception/GlobalExceptionHandler.java
  HRBank/src/main/resources/application.yaml
Labels: Feat

#40 feat: 직원 등록 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/dto/data/EmployeeDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/dto/data/EmployeeStatus.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/dto/request/EmployeeCreateRequest.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/entity/Employee.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/mapper/EmployeeMapper.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Feat

#58 refactor: seeder 인터페이스 분리
  HRBank/src/main/java/org/yebigun/hrbank/global/seeder/AllDataSeederRunner.java
  HRBank/src/main/java/org/yebigun/hrbank/global/seeder/DataSeeder.java
  HRBank/src/main/java/org/yebigun/hrbank/global/seeder/DepartmentDataSeeder.java
Labels: Refactor

#60 refactor: 인터페이스 상속하도록 수정
  HRBank/src/main/java/org/yebigun/hrbank/global/seeder/DepartmentDataSeeder.java
Labels: Refactor

#64 refactor: dto 수정, binarycontent storage 리펙터링
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/temporary/TempEmployeeDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/controller/BinaryContentController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupBinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupFileStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupFileStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
Labels: Refactor

#46 feat: 직원 이력 조회 기능 구현
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/controller/ChangeLogController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/dto/data/ChangeLogSearchCondition.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/dto/response/CursorPageResponseChangeLogDto.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/entity/ChangeLog.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/entity/ChangeLogDiff.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogDiffRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepositoryCustom.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogServiceImpl.java
Labels: Feat

#61 feat: 직원 상세 조회 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Feat

#75 refactor: 커스텀 예외 처리 생성
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/exception/DepartmentHasEmployeesException.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/exception/DuplicatedDepartmentNameException.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/global/exception/GlobalExceptionHandler.java
Labels: Refactor

#53 feat: 이력 건수 조회 컨트롤러 설계 및 명세
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/controller/ChangeLogApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/controller/ChangeLogController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/entity/PropertyName.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepositoryImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogServiceImpl.java
Labels: Feat

#72 feat: 사용하지 않는 바이너리 파일 삭제기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/controller/BackupController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/scheduler/BackupScheduler.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/scheduler/BinaryContentScheduler.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogServiceImpl.java
Labels: Feat

#65 feat: 직원 삭제 기능 구현
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeApi.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Feat

#81 refactor: transactional 어노테이션 누락 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/service/BinaryContentServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupFileStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
Labels: Refactor

#79 feat: 직원 수정 기능 추가
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorage.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BinaryContentStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/controller/EmployeeController.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/dto/request/EmployeeUpdateRequest.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeService.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: Feat

#85 feat: 백업파일 생성 변경감지 방식 수정
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/repository/BackupRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/backup/service/BackupServiceImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/repository/ChangeLogRepository.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepository.java
  HRBank/src/main/resources/schema.sql
Labels: Feat

#87 refactor: ChangeLog의 변경 필드가 비어있어도, 메모 수정 시 이력 정보 저장하도록 수정
  HRBank/src/main/java/org/yebigun/hrbank/domain/changelog/service/ChangeLogServiceImpl.java
Labels: Refactor

#89 다운로드 파일 꺠지는 문제 수정
  .idea/vcs.xml
  HRBank/src/main/java/org/yebigun/hrbank/domain/binaryContent/storage/BackupFileStorageImpl.java
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/repository/EmployeeRepositoryImpl.java
  HRBank/src/main/resources/application-deploy.yml
  HRBank/src/main/resources/application-dev.yml
  HRBank/src/main/resources/application.yml
  HRBank/src/main/resources/static/favicon.ico
  README.md
Labels: Bug

#91 refactor: 직원 등록 이름 중복 허용
  HRBank/src/main/java/org/yebigun/hrbank/domain/employee/entity/Employee.java
Labels: Refactor

#93 refactor: 커서 url-safe한 디코드 및 인코드 로직 사용
  HRBank/src/main/java/org/yebigun/hrbank/domain/department/service/DepartmentServiceImpl.java
  HRBank/src/main/resources/schema.sql
Labels: Refactor
